import { FaFacebook, FaInstagram, FaLinkedin, FaYoutube } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";

export const navMenuList = [
  {
    id: 1,
    name: "News",
    link: "/news",
  },
  {
    id: 2,
    name: "Lists",
    link: "/lists",
  },
  {
    id: 3,
    name: "Life",
    link: "/life",
  },
  {
    id: 4,
    name: "Magazine",
    link: "/magazine",
  },
];

export const socialLinks = [
  {
    id: 1,
    icon: <FaFacebook size={28} color="#fff" />,
    link: "https://www.facebook.com",
  },
  {
    id: 2,
    icon: <FaXTwitter size={28} color="#fff" />,
    link: "https://www.twitter.com",
  },
  {
    id: 3,
    icon: <FaInstagram size={28} color="#fff" />,
    link: "https://www.instagram.com",
  },
  {
    id: 4,
    icon: <FaLinkedin size={28} color="#fff" />,
    link: "https://www.linkedin.com",
  },
  {
    id: 5,
    icon: <FaYoutube size={28} color="#fff" />,
    link: "https://www.youtube.com",
  },
];

export const newsData = [
  // ==================== 01 to 10 =========================
  {
    id: "nws001",
    title: "Global Politics Takes a New Turn",
    slug: "global-politics-new-turn",
    content: "Full content of the news article goes here...",
    excerpt:
      "World leaders meet to discuss the future of international relations.",
    thumbnail: "/images/thumb/thumb1.avif",
    bannerImage: "/images/banners/politics1.jpg",
    category: "Human Capital",
    tags: ["Politics", "World", "Diplomacy"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-05-10T08:00:00Z",
    updatedAt: "2025-04-21T10:00:00Z",
    isFeatured: true,
    isEditorsPick: false,
    isBreaking: false,
    views: 2541,
    status: "published",
  },
  {
    id: "nws002",
    title: "Tech Giants Compete Over AI Domination",
    slug: "ai-domination-tech-giants",
    content: "AI advancements are creating fierce competition...",
    excerpt:
      "Google, Microsoft, and OpenAI in a heated race to lead the AI revolution.",
    thumbnail: "/images/thumb/thumb2.avif",
    bannerImage: "/images/banners/tech2.jpg",
    category: "Technology",
    tags: ["AI", "Tech", "Innovation"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-21T12:30:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1345,
    status: "unpublished",
  },
  {
    id: "nws003",
    title: "Economic Forecast Predicts Slow Recovery",
    slug: "economic-forecast-2025",
    content: "Experts believe inflation will gradually ease...",
    excerpt: "Markets remain volatile amid uncertain global outlook.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Business",
    tags: ["Economy", "Forecast", "Finance"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-19T09:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 876,
    status: "published",
  },
  {
    id: "nws004",
    title: "Champions League Final Set to Thrill Fans",
    slug: "champions-league-final-2025",
    content:
      "Two legendary teams will face off in the biggest football event...",
    excerpt: "Europe’s top football clubs clash in the ultimate showdown.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Forbes Network",
    tags: ["Football", "Champions League", "Final"],
    author: {
      id: "auth004",
      name: "Alex Morgan",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-18T14:45:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 3112,
    status: "unpublished",
  },
  {
    id: "nws005",
    title: "Oscars 2025: Top Contenders Revealed",
    slug: "oscars-2025-contenders",
    content: "The Academy announces this year’s most awaited films...",
    excerpt:
      "From drama to sci-fi, these films are leading the race for awards.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Forbes Life",
    tags: ["Oscars", "Movies", "Hollywood"],
    author: {
      id: "auth005",
      name: "Emma Thomas",
      avatar: "/images/authors/emma.jpg",
    },
    createdAt: "2025-04-17T11:20:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 920,
    status: "published",
  },
  {
    id: "nws006",
    title: "NASA Plans New Lunar Mission",
    slug: "nasa-lunar-mission-2025",
    content: "NASA aims to establish permanent base on the moon by 2030...",
    excerpt: "Next step in space exploration: Moon base in development.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Forbes Women",
    tags: ["NASA", "Moon", "Space"],
    author: {
      id: "auth006",
      name: "Neil Carter",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T09:00:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1987,
    status: "unpublished",
  },
  {
    id: "nws007",
    title: "Climate Change Impacts Crop Production",
    slug: "climate-change-agriculture",
    content: "Farmers face uncertainty due to erratic weather...",
    excerpt: "Changing climate threatens global food security.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Environment",
    tags: ["Climate", "Agriculture", "Environment"],
    author: {
      id: "auth007",
      name: "Linda Green",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T16:40:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1450,
    status: "published",
  },
  {
    id: "nws008",
    title: "Stock Market Sees Sudden Drop",
    slug: "stock-market-drop-2025",
    content: "Unexpected sell-off hits major global indices...",
    excerpt: "Investors react to latest inflation data and Fed comments.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Finance",
    tags: ["Stock Market", "Inflation", "Economy"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T06:10:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1104,
    status: "published",
  },
  {
    id: "nws009",
    title: "Meta Launches New VR Headset",
    slug: "meta-vr-headset-2025",
    content: "New features include retina tracking and haptic feedback...",
    excerpt: "The tech giant redefines virtual reality experience.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Technology",
    tags: ["Meta", "VR", "Gadgets"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T13:25:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1675,
    status: "published",
  },
  {
    id: "nws010",
    title: "UK Elections: Close Race Expected",
    slug: "uk-election-2025",
    content: "Polls suggest a tight contest between parties...",
    excerpt: "Public opinion divided ahead of key national vote.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Politics",
    tags: ["Elections", "UK", "Politics"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T08:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: true,
    views: 2110,
    status: "published",
  },

  // ==================== 11 to 20 =========================
  {
    id: "nws011",
    title: "Global Politics Takes a New Turn",
    slug: "global-politics-new-turn",
    content: "Full content of the news article goes here...",
    excerpt:
      "World leaders meet to discuss the future of international relations.",
    thumbnail: "/images/thumb/thumb1.avif",
    bannerImage: "/images/banners/politics1.jpg",
    category: "International",
    tags: ["Politics", "World", "Diplomacy"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-05-20T08:00:00Z",
    updatedAt: "2025-04-21T10:00:00Z",
    isFeatured: true,
    isEditorsPick: false,
    isBreaking: false,
    views: 2541,
    status: "published",
  },
  {
    id: "nws012",
    title: "Tech Giants Compete Over AI Domination",
    slug: "ai-domination-tech-giants",
    content: "AI advancements are creating fierce competition...",
    excerpt:
      "Google, Microsoft, and OpenAI in a heated race to lead the AI revolution.",
    thumbnail: "/images/thumb/thumb2.avif",
    bannerImage: "/images/banners/tech2.jpg",
    category: "Technology",
    tags: ["AI", "Tech", "Innovation"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-21T12:30:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1345,
    status: "published",
  },
  {
    id: "nws013",
    title: "Economic Forecast Predicts Slow Recovery",
    slug: "economic-forecast-2025",
    content: "Experts believe inflation will gradually ease...",
    excerpt: "Markets remain volatile amid uncertain global outlook.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Business",
    tags: ["Economy", "Forecast", "Finance"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-19T09:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 876,
    status: "published",
  },
  {
    id: "nws014",
    title: "Champions League Final Set to Thrill Fans",
    slug: "champions-league-final-2025",
    content:
      "Two legendary teams will face off in the biggest football event...",
    excerpt: "Europe’s top football clubs clash in the ultimate showdown.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Sports",
    tags: ["Football", "Champions League", "Final"],
    author: {
      id: "auth004",
      name: "Alex Morgan",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-18T14:45:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 3112,
    status: "published",
  },
  {
    id: "nws015",
    title: "Oscars 2025: Top Contenders Revealed",
    slug: "oscars-2025-contenders",
    content: "The Academy announces this year’s most awaited films...",
    excerpt:
      "From drama to sci-fi, these films are leading the race for awards.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Entertainment",
    tags: ["Oscars", "Movies", "Hollywood"],
    author: {
      id: "auth005",
      name: "Emma Thomas",
      avatar: "/images/authors/emma.jpg",
    },
    createdAt: "2025-04-17T11:20:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 920,
    status: "published",
  },
  {
    id: "nws016",
    title: "NASA Plans New Lunar Mission",
    slug: "nasa-lunar-mission-2025",
    content: "NASA aims to establish permanent base on the moon by 2030...",
    excerpt: "Next step in space exploration: Moon base in development.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Forbes Women",
    tags: ["NASA", "Moon", "Space"],
    author: {
      id: "auth006",
      name: "Neil Carter",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T09:00:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1987,
    status: "published",
  },
  {
    id: "nws017",
    title: "Climate Change Impacts Crop Production",
    slug: "climate-change-agriculture",
    content: "Farmers face uncertainty due to erratic weather...",
    excerpt: "Changing climate threatens global food security.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Environment",
    tags: ["Climate", "Agriculture", "Environment"],
    author: {
      id: "auth007",
      name: "Linda Green",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T16:40:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1450,
    status: "published",
  },
  {
    id: "nws018",
    title: "Stock Market Sees Sudden Drop",
    slug: "stock-market-drop-2025",
    content: "Unexpected sell-off hits major global indices...",
    excerpt: "Investors react to latest inflation data and Fed comments.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Finance",
    tags: ["Stock Market", "Inflation", "Economy"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T06:10:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1104,
    status: "published",
  },
  {
    id: "nws019",
    title: "Meta Launches New VR Headset",
    slug: "meta-vr-headset-2025",
    content: "New features include retina tracking and haptic feedback...",
    excerpt: "The tech giant redefines virtual reality experience.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Technology",
    tags: ["Meta", "VR", "Gadgets"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T13:25:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1675,
    status: "published",
  },
  {
    id: "nws020",
    title: "UK Elections: Close Race Expected",
    slug: "uk-election-2025",
    content: "Polls suggest a tight contest between parties...",
    excerpt: "Public opinion divided ahead of key national vote.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Politics",
    tags: ["Elections", "UK", "Politics"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T08:15:00Z",
    isFeatured: false,
    isEditorsPick: true,
    isBreaking: false,
    views: 2110,
    status: "published",
  },

  // ==================== 21 to 30 =========================
  {
    id: "nws021",
    title: "Global Politics Takes a New Turn",
    slug: "global-politics-new-turn",
    content: "Full content of the news article goes here...",
    excerpt:
      "World leaders meet to discuss the future of international relations.",
    thumbnail: "/images/thumb/thumb1.avif",
    bannerImage: "/images/banners/politics1.jpg",
    category: "International",
    tags: ["Politics", "World", "Diplomacy"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T08:00:00Z",
    updatedAt: "2025-04-21T10:00:00Z",
    isFeatured: true,
    isEditorsPick: false,
    isBreaking: false,
    views: 2541,
    status: "published",
  },
  {
    id: "nws022",
    title: "Tech Giants Compete Over AI Domination",
    slug: "ai-domination-tech-giants",
    content: "AI advancements are creating fierce competition...",
    excerpt:
      "Google, Microsoft, and OpenAI in a heated race to lead the AI revolution.",
    thumbnail: "/images/thumb/thumb2.avif",
    bannerImage: "/images/banners/tech2.jpg",
    category: "Technology",
    tags: ["AI", "Tech", "Innovation"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-21T12:30:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 1345,
    status: "published",
  },
  {
    id: "nws023",
    title: "Economic Forecast Predicts Slow Recovery",
    slug: "economic-forecast-2025",
    content: "Experts believe inflation will gradually ease...",
    excerpt: "Markets remain volatile amid uncertain global outlook.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Business",
    tags: ["Economy", "Forecast", "Finance"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-19T09:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    isBreaking: false,
    views: 876,
    status: "published",
  },
  {
    id: "nws024",
    title: "Champions League Final Set to Thrill Fans",
    slug: "champions-league-final-2025",
    content:
      "Two legendary teams will face off in the biggest football event...",
    excerpt: "Europe’s top football clubs clash in the ultimate showdown.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Sports",
    tags: ["Football", "Champions League", "Final"],
    author: {
      id: "auth004",
      name: "Alex Morgan",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-18T14:45:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 3112,
    status: "published",
  },
  {
    id: "nws025",
    title: "Oscars 2025: Top Contenders Revealed",
    slug: "oscars-2025-contenders",
    content: "The Academy announces this year’s most awaited films...",
    excerpt:
      "From drama to sci-fi, these films are leading the race for awards.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Entertainment",
    tags: ["Oscars", "Movies", "Hollywood"],
    author: {
      id: "auth005",
      name: "Emma Thomas",
      avatar: "/images/authors/emma.jpg",
    },
    createdAt: "2025-04-17T11:20:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 920,
    status: "published",
  },
  {
    id: "nws026",
    title: "NASA Plans New Lunar Mission",
    slug: "nasa-lunar-mission-2025",
    content: "NASA aims to establish permanent base on the moon by 2030...",
    excerpt: "Next step in space exploration: Moon base in development.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Forbes Women",
    tags: ["NASA", "Moon", "Space"],
    author: {
      id: "auth006",
      name: "Neil Carter",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T09:00:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1987,
    status: "published",
  },
  {
    id: "nws027",
    title: "Climate Change Impacts Crop Production",
    slug: "climate-change-agriculture",
    content: "Farmers face uncertainty due to erratic weather...",
    excerpt: "Changing climate threatens global food security.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Environment",
    tags: ["Climate", "Agriculture", "Environment"],
    author: {
      id: "auth007",
      name: "Linda Green",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T16:40:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1450,
    status: "published",
  },
  {
    id: "nws028",
    title: "Stock Market Sees Sudden Drop",
    slug: "stock-market-drop-2025",
    content: "Unexpected sell-off hits major global indices...",
    excerpt: "Investors react to latest inflation data and Fed comments.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Finance",
    tags: ["Stock Market", "Inflation", "Economy"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T06:10:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1104,
    status: "published",
  },
  {
    id: "nws029",
    title: "Meta Launches New VR Headset",
    slug: "meta-vr-headset-2025",
    content: "New features include retina tracking and haptic feedback...",
    excerpt: "The tech giant redefines virtual reality experience.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Technology",
    tags: ["Meta", "VR", "Gadgets"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T13:25:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1675,
    status: "published",
  },
  {
    id: "nws030",
    title: "UK Elections: Close Race Expected",
    slug: "uk-election-2025",
    content: "Polls suggest a tight contest between parties...",
    excerpt: "Public opinion divided ahead of key national vote.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Politics",
    tags: ["Elections", "UK", "Politics"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T08:15:00Z",
    isFeatured: false,
    isEditorsPick: true,
    views: 2110,
    status: "published",
  },

  // ==================== 31 to 40 =========================
  {
    id: "nws031",
    title: "Global Politics Takes a New Turn",
    slug: "global-politics-new-turn",
    content: "Full content of the news article goes here...",
    excerpt:
      "World leaders meet to discuss the future of international relations.",
    thumbnail: "/images/thumb/thumb1.avif",
    bannerImage: "/images/banners/politics1.jpg",
    category: "International",
    tags: ["Politics", "World", "Diplomacy"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T08:00:00Z",
    updatedAt: "2025-04-21T10:00:00Z",
    isFeatured: true,
    isEditorsPick: false,
    views: 2541,
    status: "published",
  },
  {
    id: "nws032",
    title: "Tech Giants Compete Over AI Domination",
    slug: "ai-domination-tech-giants",
    content: "AI advancements are creating fierce competition...",
    excerpt:
      "Google, Microsoft, and OpenAI in a heated race to lead the AI revolution.",
    thumbnail: "/images/thumb/thumb2.avif",
    bannerImage: "/images/banners/tech2.jpg",
    category: "Technology",
    tags: ["AI", "Tech", "Innovation"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-21T12:30:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1345,
    status: "published",
  },
  {
    id: "nws033",
    title: "Economic Forecast Predicts Slow Recovery",
    slug: "economic-forecast-2025",
    content: "Experts believe inflation will gradually ease...",
    excerpt: "Markets remain volatile amid uncertain global outlook.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Business",
    tags: ["Economy", "Forecast", "Finance"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-19T09:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 876,
    status: "published",
  },
  {
    id: "nws034",
    title: "Champions League Final Set to Thrill Fans",
    slug: "champions-league-final-2025",
    content:
      "Two legendary teams will face off in the biggest football event...",
    excerpt: "Europe’s top football clubs clash in the ultimate showdown.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Sports",
    tags: ["Football", "Champions League", "Final"],
    author: {
      id: "auth004",
      name: "Alex Morgan",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-18T14:45:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 3112,
    status: "published",
  },
  {
    id: "nws035",
    title: "Oscars 2025: Top Contenders Revealed",
    slug: "oscars-2025-contenders",
    content: "The Academy announces this year’s most awaited films...",
    excerpt:
      "From drama to sci-fi, these films are leading the race for awards.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Entertainment",
    tags: ["Oscars", "Movies", "Hollywood"],
    author: {
      id: "auth005",
      name: "Emma Thomas",
      avatar: "/images/authors/emma.jpg",
    },
    createdAt: "2025-04-17T11:20:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 920,
    status: "published",
  },
  {
    id: "nws036",
    title: "NASA Plans New Lunar Mission",
    slug: "nasa-lunar-mission-2025",
    content: "NASA aims to establish permanent base on the moon by 2030...",
    excerpt: "Next step in space exploration: Moon base in development.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Forbes Women",
    tags: ["NASA", "Moon", "Space"],
    author: {
      id: "auth006",
      name: "Neil Carter",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T09:00:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1987,
    status: "published",
  },
  {
    id: "nws037",
    title: "Climate Change Impacts Crop Production",
    slug: "climate-change-agriculture",
    content: "Farmers face uncertainty due to erratic weather...",
    excerpt: "Changing climate threatens global food security.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Environment",
    tags: ["Climate", "Agriculture", "Environment"],
    author: {
      id: "auth007",
      name: "Linda Green",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T16:40:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1450,
    status: "published",
  },
  {
    id: "nws038",
    title: "Stock Market Sees Sudden Drop",
    slug: "stock-market-drop-2025",
    content: "Unexpected sell-off hits major global indices...",
    excerpt: "Investors react to latest inflation data and Fed comments.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Finance",
    tags: ["Stock Market", "Inflation", "Economy"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T06:10:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1104,
    status: "published",
  },
  {
    id: "nws039",
    title: "Meta Launches New VR Headset",
    slug: "meta-vr-headset-2025",
    content: "New features include retina tracking and haptic feedback...",
    excerpt: "The tech giant redefines virtual reality experience.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Technology",
    tags: ["Meta", "VR", "Gadgets"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T13:25:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1675,
    status: "published",
  },
  {
    id: "nws040",
    title: "UK Elections: Close Race Expected",
    slug: "uk-election-2025",
    content: "Polls suggest a tight contest between parties...",
    excerpt: "Public opinion divided ahead of key national vote.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Politics",
    tags: ["Elections", "UK", "Politics"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T08:15:00Z",
    isFeatured: false,
    isEditorsPick: true,
    views: 2110,
    status: "published",
  },

  // ==================== 41 to 50 =========================
  {
    id: "nws041",
    title: "Global Politics Takes a New Turn",
    slug: "global-politics-new-turn",
    content: "Full content of the news article goes here...",
    excerpt:
      "World leaders meet to discuss the future of international relations.",
    thumbnail: "/images/thumb/thumb1.avif",
    bannerImage: "/images/banners/politics1.jpg",
    category: "International",
    tags: ["Politics", "World", "Diplomacy"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T08:00:00Z",
    updatedAt: "2025-04-21T10:00:00Z",
    isFeatured: true,
    isEditorsPick: false,
    views: 2541,
    status: "published",
  },
  {
    id: "nws042",
    title: "Tech Giants Compete Over AI Domination",
    slug: "ai-domination-tech-giants",
    content: "AI advancements are creating fierce competition...",
    excerpt:
      "Google, Microsoft, and OpenAI in a heated race to lead the AI revolution.",
    thumbnail: "/images/thumb/thumb2.avif",
    bannerImage: "/images/banners/tech2.jpg",
    category: "Technology",
    tags: ["AI", "Tech", "Innovation"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-21T12:30:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1345,
    status: "published",
  },
  {
    id: "nws043",
    title: "Economic Forecast Predicts Slow Recovery",
    slug: "economic-forecast-2025",
    content: "Experts believe inflation will gradually ease...",
    excerpt: "Markets remain volatile amid uncertain global outlook.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Business",
    tags: ["Economy", "Forecast", "Finance"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-19T09:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 876,
    status: "published",
  },
  {
    id: "nws044",
    title: "Champions League Final Set to Thrill Fans",
    slug: "champions-league-final-2025",
    content:
      "Two legendary teams will face off in the biggest football event...",
    excerpt: "Europe’s top football clubs clash in the ultimate showdown.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Sports",
    tags: ["Football", "Champions League", "Final"],
    author: {
      id: "auth004",
      name: "Alex Morgan",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-18T14:45:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 3112,
    status: "published",
  },
  {
    id: "nws045",
    title: "Oscars 2025: Top Contenders Revealed",
    slug: "oscars-2025-contenders",
    content: "The Academy announces this year’s most awaited films...",
    excerpt:
      "From drama to sci-fi, these films are leading the race for awards.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Entertainment",
    tags: ["Oscars", "Movies", "Hollywood"],
    author: {
      id: "auth005",
      name: "Emma Thomas",
      avatar: "/images/authors/emma.jpg",
    },
    createdAt: "2025-04-17T11:20:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 920,
    status: "published",
  },
  {
    id: "nws046",
    title: "NASA Plans New Lunar Mission",
    slug: "nasa-lunar-mission-2025",
    content: "NASA aims to establish permanent base on the moon by 2030...",
    excerpt: "Next step in space exploration: Moon base in development.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Forbes Women",
    tags: ["NASA", "Moon", "Space"],
    author: {
      id: "auth006",
      name: "Neil Carter",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T09:00:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1987,
    status: "published",
  },
  {
    id: "nws047",
    title: "Climate Change Impacts Crop Production",
    slug: "climate-change-agriculture",
    content: "Farmers face uncertainty due to erratic weather...",
    excerpt: "Changing climate threatens global food security.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Environment",
    tags: ["Climate", "Agriculture", "Environment"],
    author: {
      id: "auth007",
      name: "Linda Green",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T16:40:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1450,
    status: "published",
  },
  {
    id: "nws048",
    title: "Stock Market Sees Sudden Drop",
    slug: "stock-market-drop-2025",
    content: "Unexpected sell-off hits major global indices...",
    excerpt: "Investors react to latest inflation data and Fed comments.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Finance",
    tags: ["Stock Market", "Inflation", "Economy"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T06:10:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1104,
    status: "published",
  },
  {
    id: "nws049",
    title: "Meta Launches New VR Headset",
    slug: "meta-vr-headset-2025",
    content: "New features include retina tracking and haptic feedback...",
    excerpt: "The tech giant redefines virtual reality experience.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Technology",
    tags: ["Meta", "VR", "Gadgets"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T13:25:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1675,
    status: "published",
  },
  {
    id: "nws050",
    title: "UK Elections: Close Race Expected",
    slug: "uk-election-2025",
    content: "Polls suggest a tight contest between parties...",
    excerpt: "Public opinion divided ahead of key national vote.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Politics",
    tags: ["Elections", "UK", "Politics"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T08:15:00Z",
    isFeatured: false,
    isEditorsPick: true,
    views: 2110,
    status: "published",
  },

  // ==================== 51 to 60 =========================
  {
    id: "nws051",
    title: "Global Politics Takes a New Turn",
    slug: "global-politics-new-turn",
    content: "Full content of the news article goes here...",
    excerpt:
      "World leaders meet to discuss the future of international relations.",
    thumbnail: "/images/thumb/thumb1.avif",
    bannerImage: "/images/banners/politics1.jpg",
    category: "International",
    tags: ["Politics", "World", "Diplomacy"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T08:00:00Z",
    updatedAt: "2025-04-21T10:00:00Z",
    isFeatured: true,
    isEditorsPick: false,
    views: 2541,
    status: "published",
  },
  {
    id: "nws052",
    title: "Tech Giants Compete Over AI Domination",
    slug: "ai-domination-tech-giants",
    content: "AI advancements are creating fierce competition...",
    excerpt:
      "Google, Microsoft, and OpenAI in a heated race to lead the AI revolution.",
    thumbnail: "/images/thumb/thumb2.avif",
    bannerImage: "/images/banners/tech2.jpg",
    category: "Technology",
    tags: ["AI", "Tech", "Innovation"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-21T12:30:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1345,
    status: "published",
  },
  {
    id: "nws053",
    title: "Economic Forecast Predicts Slow Recovery",
    slug: "economic-forecast-2025",
    content: "Experts believe inflation will gradually ease...",
    excerpt: "Markets remain volatile amid uncertain global outlook.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Business",
    tags: ["Economy", "Forecast", "Finance"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-19T09:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 876,
    status: "published",
  },
  {
    id: "nws054",
    title: "Champions League Final Set to Thrill Fans",
    slug: "champions-league-final-2025",
    content:
      "Two legendary teams will face off in the biggest football event...",
    excerpt: "Europe’s top football clubs clash in the ultimate showdown.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Sports",
    tags: ["Football", "Champions League", "Final"],
    author: {
      id: "auth004",
      name: "Alex Morgan",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-18T14:45:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 3112,
    status: "published",
  },
  {
    id: "nws055",
    title: "Oscars 2025: Top Contenders Revealed",
    slug: "oscars-2025-contenders",
    content: "The Academy announces this year’s most awaited films...",
    excerpt:
      "From drama to sci-fi, these films are leading the race for awards.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Entertainment",
    tags: ["Oscars", "Movies", "Hollywood"],
    author: {
      id: "auth005",
      name: "Emma Thomas",
      avatar: "/images/authors/emma.jpg",
    },
    createdAt: "2025-04-17T11:20:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 920,
    status: "published",
  },
  {
    id: "nws056",
    title: "NASA Plans New Lunar Mission",
    slug: "nasa-lunar-mission-2025",
    content: "NASA aims to establish permanent base on the moon by 2030...",
    excerpt: "Next step in space exploration: Moon base in development.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Forbes Women",
    tags: ["NASA", "Moon", "Space"],
    author: {
      id: "auth006",
      name: "Neil Carter",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T09:00:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1987,
    status: "published",
  },
  {
    id: "nws057",
    title: "Climate Change Impacts Crop Production",
    slug: "climate-change-agriculture",
    content: "Farmers face uncertainty due to erratic weather...",
    excerpt: "Changing climate threatens global food security.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Environment",
    tags: ["Climate", "Agriculture", "Environment"],
    author: {
      id: "auth007",
      name: "Linda Green",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T16:40:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1450,
    status: "published",
  },
  {
    id: "nws058",
    title: "Stock Market Sees Sudden Drop",
    slug: "stock-market-drop-2025",
    content: "Unexpected sell-off hits major global indices...",
    excerpt: "Investors react to latest inflation data and Fed comments.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Finance",
    tags: ["Stock Market", "Inflation", "Economy"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T06:10:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1104,
    status: "published",
  },
  {
    id: "nws059",
    title: "Meta Launches New VR Headset",
    slug: "meta-vr-headset-2025",
    content: "New features include retina tracking and haptic feedback...",
    excerpt: "The tech giant redefines virtual reality experience.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Technology",
    tags: ["Meta", "VR", "Gadgets"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T13:25:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1675,
    status: "published",
  },
  {
    id: "nws060",
    title: "UK Elections: Close Race Expected",
    slug: "uk-election-2025",
    content: "Polls suggest a tight contest between parties...",
    excerpt: "Public opinion divided ahead of key national vote.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Politics",
    tags: ["Elections", "UK", "Politics"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T08:15:00Z",
    isFeatured: false,
    isEditorsPick: true,
    views: 2110,
    status: "published",
  },

  // ==================== 61 to 70 =========================
  {
    id: "nws061",
    title: "Global Politics Takes a New Turn",
    slug: "global-politics-new-turn",
    content: "Full content of the news article goes here...",
    excerpt:
      "World leaders meet to discuss the future of international relations.",
    thumbnail: "/images/thumb/thumb1.avif",
    bannerImage: "/images/banners/politics1.jpg",
    category: "International",
    tags: ["Politics", "World", "Diplomacy"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T08:00:00Z",
    updatedAt: "2025-04-21T10:00:00Z",
    isFeatured: true,
    isEditorsPick: false,
    views: 2541,
    status: "published",
  },
  {
    id: "nws062",
    title: "Tech Giants Compete Over AI Domination",
    slug: "ai-domination-tech-giants",
    content: "AI advancements are creating fierce competition...",
    excerpt:
      "Google, Microsoft, and OpenAI in a heated race to lead the AI revolution.",
    thumbnail: "/images/thumb/thumb2.avif",
    bannerImage: "/images/banners/tech2.jpg",
    category: "Technology",
    tags: ["AI", "Tech", "Innovation"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-21T12:30:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1345,
    status: "published",
  },
  {
    id: "nws063",
    title: "Economic Forecast Predicts Slow Recovery",
    slug: "economic-forecast-2025",
    content: "Experts believe inflation will gradually ease...",
    excerpt: "Markets remain volatile amid uncertain global outlook.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Business",
    tags: ["Economy", "Forecast", "Finance"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-19T09:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 876,
    status: "published",
  },
  {
    id: "nws064",
    title: "Champions League Final Set to Thrill Fans",
    slug: "champions-league-final-2025",
    content:
      "Two legendary teams will face off in the biggest football event...",
    excerpt: "Europe’s top football clubs clash in the ultimate showdown.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Sports",
    tags: ["Football", "Champions League", "Final"],
    author: {
      id: "auth004",
      name: "Alex Morgan",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-18T14:45:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 3112,
    status: "published",
  },
  {
    id: "nws065",
    title: "Oscars 2025: Top Contenders Revealed",
    slug: "oscars-2025-contenders",
    content: "The Academy announces this year’s most awaited films...",
    excerpt:
      "From drama to sci-fi, these films are leading the race for awards.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Entertainment",
    tags: ["Oscars", "Movies", "Hollywood"],
    author: {
      id: "auth005",
      name: "Emma Thomas",
      avatar: "/images/authors/emma.jpg",
    },
    createdAt: "2025-04-17T11:20:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 920,
    status: "published",
  },
  {
    id: "nws066",
    title: "NASA Plans New Lunar Mission",
    slug: "nasa-lunar-mission-2025",
    content: "NASA aims to establish permanent base on the moon by 2030...",
    excerpt: "Next step in space exploration: Moon base in development.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Forbes Women",
    tags: ["NASA", "Moon", "Space"],
    author: {
      id: "auth006",
      name: "Neil Carter",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T09:00:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1987,
    status: "published",
  },
  {
    id: "nws067",
    title: "Climate Change Impacts Crop Production",
    slug: "climate-change-agriculture",
    content: "Farmers face uncertainty due to erratic weather...",
    excerpt: "Changing climate threatens global food security.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Environment",
    tags: ["Climate", "Agriculture", "Environment"],
    author: {
      id: "auth007",
      name: "Linda Green",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T16:40:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1450,
    status: "published",
  },
  {
    id: "nws068",
    title: "Stock Market Sees Sudden Drop",
    slug: "stock-market-drop-2025",
    content: "Unexpected sell-off hits major global indices...",
    excerpt: "Investors react to latest inflation data and Fed comments.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Finance",
    tags: ["Stock Market", "Inflation", "Economy"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T06:10:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1104,
    status: "published",
  },
  {
    id: "nws069",
    title: "Meta Launches New VR Headset",
    slug: "meta-vr-headset-2025",
    content: "New features include retina tracking and haptic feedback...",
    excerpt: "The tech giant redefines virtual reality experience.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Technology",
    tags: ["Meta", "VR", "Gadgets"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T13:25:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1675,
    status: "published",
  },
  {
    id: "nws070",
    title: "UK Elections: Close Race Expected",
    slug: "uk-election-2025",
    content: "Polls suggest a tight contest between parties...",
    excerpt: "Public opinion divided ahead of key national vote.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Politics",
    tags: ["Elections", "UK", "Politics"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T08:15:00Z",
    isFeatured: false,
    isEditorsPick: true,
    views: 2110,
    status: "published",
  },

  // ==================== 71 to 80 =========================
  {
    id: "nws071",
    title: "Global Politics Takes a New Turn",
    slug: "global-politics-new-turn",
    content: "Full content of the news article goes here...",
    excerpt:
      "World leaders meet to discuss the future of international relations.",
    thumbnail: "/images/thumb/thumb1.avif",
    bannerImage: "/images/banners/politics1.jpg",
    category: "International",
    tags: ["Politics", "World", "Diplomacy"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T08:00:00Z",
    updatedAt: "2025-04-21T10:00:00Z",
    isFeatured: true,
    isEditorsPick: false,
    views: 2541,
    status: "published",
  },
  {
    id: "nws072",
    title: "Tech Giants Compete Over AI Domination",
    slug: "ai-domination-tech-giants",
    content: "AI advancements are creating fierce competition...",
    excerpt:
      "Google, Microsoft, and OpenAI in a heated race to lead the AI revolution.",
    thumbnail: "/images/thumb/thumb2.avif",
    bannerImage: "/images/banners/tech2.jpg",
    category: "Technology",
    tags: ["AI", "Tech", "Innovation"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-21T12:30:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1345,
    status: "published",
  },
  {
    id: "nws073",
    title: "Economic Forecast Predicts Slow Recovery",
    slug: "economic-forecast-2025",
    content: "Experts believe inflation will gradually ease...",
    excerpt: "Markets remain volatile amid uncertain global outlook.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Business",
    tags: ["Economy", "Forecast", "Finance"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-19T09:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 876,
    status: "published",
  },
  {
    id: "nws0074",
    title: "Champions League Final Set to Thrill Fans",
    slug: "champions-league-final-2025",
    content:
      "Two legendary teams will face off in the biggest football event...",
    excerpt: "Europe’s top football clubs clash in the ultimate showdown.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Sports",
    tags: ["Football", "Champions League", "Final"],
    author: {
      id: "auth004",
      name: "Alex Morgan",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-18T14:45:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 3112,
    status: "published",
  },
  {
    id: "nws075",
    title: "Oscars 2025: Top Contenders Revealed",
    slug: "oscars-2025-contenders",
    content: "The Academy announces this year’s most awaited films...",
    excerpt:
      "From drama to sci-fi, these films are leading the race for awards.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Entertainment",
    tags: ["Oscars", "Movies", "Hollywood"],
    author: {
      id: "auth005",
      name: "Emma Thomas",
      avatar: "/images/authors/emma.jpg",
    },
    createdAt: "2025-04-17T11:20:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 920,
    status: "published",
  },
  {
    id: "nws076",
    title: "NASA Plans New Lunar Mission",
    slug: "nasa-lunar-mission-2025",
    content: "NASA aims to establish permanent base on the moon by 2030...",
    excerpt: "Next step in space exploration: Moon base in development.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Forbes Women",
    tags: ["NASA", "Moon", "Space"],
    author: {
      id: "auth006",
      name: "Neil Carter",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T09:00:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1987,
    status: "published",
  },
  {
    id: "nws077",
    title: "Climate Change Impacts Crop Production",
    slug: "climate-change-agriculture",
    content: "Farmers face uncertainty due to erratic weather...",
    excerpt: "Changing climate threatens global food security.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Environment",
    tags: ["Climate", "Agriculture", "Environment"],
    author: {
      id: "auth007",
      name: "Linda Green",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T16:40:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1450,
    status: "published",
  },
  {
    id: "nws078",
    title: "Stock Market Sees Sudden Drop",
    slug: "stock-market-drop-2025",
    content: "Unexpected sell-off hits major global indices...",
    excerpt: "Investors react to latest inflation data and Fed comments.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Finance",
    tags: ["Stock Market", "Inflation", "Economy"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T06:10:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1104,
    status: "published",
  },
  {
    id: "nws079",
    title: "Meta Launches New VR Headset",
    slug: "meta-vr-headset-2025",
    content: "New features include retina tracking and haptic feedback...",
    excerpt: "The tech giant redefines virtual reality experience.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Technology",
    tags: ["Meta", "VR", "Gadgets"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-22T13:25:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1675,
    status: "published",
  },
  {
    id: "nws080",
    title: "UK Elections: Close Race Expected",
    slug: "uk-election-2025",
    content: "Polls suggest a tight contest between parties...",
    excerpt: "Public opinion divided ahead of key national vote.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Politics",
    tags: ["Elections", "UK", "Politics"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T08:15:00Z",
    isFeatured: false,
    isEditorsPick: true,
    views: 2110,
    status: "published",
  },

  // ====================== 81 to 90 ========================
  {
    id: "nws081",
    title: "Global Politics Takes a New Turn",
    slug: "global-politics-new-turn",
    content: "Full content of the news article goes here...",
    excerpt:
      "World leaders meet to discuss the future of international relations.",
    thumbnail: "/images/thumb/thumb1.avif",
    bannerImage: "/images/banners/politics1.jpg",
    category: "International",
    tags: ["Politics", "World", "Diplomacy"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T08:00:00Z",
    updatedAt: "2025-04-21T10:00:00Z",
    isFeatured: true,
    isEditorsPick: false,
    views: 2541,
    status: "published",
  },
  {
    id: "nws082",
    title: "Tech Giants Compete Over AI Domination",
    slug: "ai-domination-tech-giants",
    content: "AI advancements are creating fierce competition...",
    excerpt:
      "Google, Microsoft, and OpenAI in a heated race to lead the AI revolution.",
    thumbnail: "/images/thumb/thumb2.avif",
    bannerImage: "/images/banners/tech2.jpg",
    category: "Technology",
    tags: ["AI", "Tech", "Innovation"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-26T12:30:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1345,
    status: "published",
  },
  {
    id: "nws083",
    title: "Economic Forecast Predicts Slow Recovery",
    slug: "economic-forecast-2025",
    content: "Experts believe inflation will gradually ease...",
    excerpt: "Markets remain volatile amid uncertain global outlook.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Business",
    tags: ["Economy", "Forecast", "Finance"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-26T09:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 876,
    status: "published",
  },
  {
    id: "nws084",
    title: "Champions League Final Set to Thrill Fans",
    slug: "champions-league-final-2025",
    content:
      "Two legendary teams will face off in the biggest football event...",
    excerpt: "Europe’s top football clubs clash in the ultimate showdown.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Sports",
    tags: ["Football", "Champions League", "Final"],
    author: {
      id: "auth004",
      name: "Alex Morgan",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-26T14:45:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 3112,
    status: "published",
  },
  {
    id: "nws085",
    title: "Oscars 2025: Top Contenders Revealed",
    slug: "oscars-2025-contenders",
    content: "The Academy announces this year’s most awaited films...",
    excerpt:
      "From drama to sci-fi, these films are leading the race for awards.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Entertainment",
    tags: ["Oscars", "Movies", "Hollywood"],
    author: {
      id: "auth005",
      name: "Emma Thomas",
      avatar: "/images/authors/emma.jpg",
    },
    createdAt: "2025-04-26T11:20:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 920,
    status: "published",
  },
  {
    id: "nws086",
    title: "NASA Plans New Lunar Mission",
    slug: "nasa-lunar-mission-2025",
    content: "NASA aims to establish permanent base on the moon by 2030...",
    excerpt: "Next step in space exploration: Moon base in development.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Science",
    tags: ["NASA", "Moon", "Space"],
    author: {
      id: "auth006",
      name: "Neil Carter",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-26T09:00:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1987,
    status: "published",
  },
  {
    id: "nws087",
    title: "Climate Change Impacts Crop Production",
    slug: "climate-change-agriculture",
    content: "Farmers face uncertainty due to erratic weather...",
    excerpt: "Changing climate threatens global food security.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Environment",
    tags: ["Climate", "Agriculture", "Environment"],
    author: {
      id: "auth007",
      name: "Linda Green",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-26T16:40:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1450,
    status: "published",
  },
  {
    id: "nws088",
    title: "Stock Market Sees Sudden Drop",
    slug: "stock-market-drop-2025",
    content: "Unexpected sell-off hits major global indices...",
    excerpt: "Investors react to latest inflation data and Fed comments.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Finance",
    tags: ["Stock Market", "Inflation", "Economy"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-26T06:10:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1104,
    status: "published",
  },
  {
    id: "nws089",
    title: "Meta Launches New VR Headset",
    slug: "meta-vr-headset-2025",
    content: "New features include retina tracking and haptic feedback...",
    excerpt: "The tech giant redefines virtual reality experience.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Technology",
    tags: ["Meta", "VR", "Gadgets"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-26T13:25:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1675,
    status: "published",
  },
  {
    id: "nws090",
    title: "UK Elections: Close Race Expected",
    slug: "uk-election-2025",
    content: "Polls suggest a tight contest between parties...",
    excerpt: "Public opinion divided ahead of key national vote.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Politics",
    tags: ["Elections", "UK", "Politics"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T08:15:00Z",
    isFeatured: false,
    isEditorsPick: true,
    views: 2110,
    status: "published",
  },

  // ======================== 91 to 100 ====================================
  {
    id: "nws091",
    title: "Global Politics Takes a New Turn",
    slug: "global-politics-new-turn",
    content: "Full content of the news article goes here...",
    excerpt:
      "World leaders meet to discuss the future of international relations.",
    thumbnail: "/images/thumb/thumb1.avif",
    bannerImage: "/images/banners/politics1.jpg",
    category: "International",
    tags: ["Politics", "World", "Diplomacy"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-20T08:00:00Z",
    updatedAt: "2025-04-21T10:00:00Z",
    isFeatured: true,
    isEditorsPick: false,
    views: 2541,
    status: "published",
  },
  {
    id: "nws092",
    title: "Tech Giants Compete Over AI Domination",
    slug: "ai-domination-tech-giants",
    content: "AI advancements are creating fierce competition...",
    excerpt:
      "Google, Microsoft, and OpenAI in a heated race to lead the AI revolution.",
    thumbnail: "/images/thumb/thumb2.avif",
    bannerImage: "/images/banners/tech2.jpg",
    category: "Technology",
    tags: ["AI", "Tech", "Innovation"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-27T12:30:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1345,
    status: "published",
  },
  {
    id: "nws093",
    title: "Economic Forecast Predicts Slow Recovery",
    slug: "economic-forecast-2025",
    content: "Experts believe inflation will gradually ease...",
    excerpt: "Markets remain volatile amid uncertain global outlook.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Business",
    tags: ["Economy", "Forecast", "Finance"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-27T09:15:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 876,
    status: "published",
  },
  {
    id: "nws094",
    title: "Champions League Final Set to Thrill Fans",
    slug: "champions-league-final-2025",
    content:
      "Two legendary teams will face off in the biggest football event...",
    excerpt: "Europe’s top football clubs clash in the ultimate showdown.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Sports",
    tags: ["Football", "Champions League", "Final"],
    author: {
      id: "auth004",
      name: "Alex Morgan",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-27T14:45:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 3112,
    status: "published",
  },
  {
    id: "nws095",
    title: "Oscars 2025: Top Contenders Revealed",
    slug: "oscars-2025-contenders",
    content: "The Academy announces this year’s most awaited films...",
    excerpt:
      "From drama to sci-fi, these films are leading the race for awards.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Entertainment",
    tags: ["Oscars", "Movies", "Hollywood"],
    author: {
      id: "auth005",
      name: "Emma Thomas",
      avatar: "/images/authors/emma.jpg",
    },
    createdAt: "2025-04-27T11:20:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 920,
    status: "published",
  },
  {
    id: "nws096",
    title: "NASA Plans New Lunar Mission",
    slug: "nasa-lunar-mission-2025",
    content: "NASA aims to establish permanent base on the moon by 2030...",
    excerpt: "Next step in space exploration: Moon base in development.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Science",
    tags: ["NASA", "Moon", "Space"],
    author: {
      id: "auth006",
      name: "Neil Carter",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-27T09:00:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1987,
    status: "published",
  },
  {
    id: "nws097",
    title: "Climate Change Impacts Crop Production",
    slug: "climate-change-agriculture",
    content: "Farmers face uncertainty due to erratic weather...",
    excerpt: "Changing climate threatens global food security.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Environment",
    tags: ["Climate", "Agriculture", "Environment"],
    author: {
      id: "auth007",
      name: "Linda Green",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-27T16:40:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1450,
    status: "published",
  },
  {
    id: "nws098",
    title: "Stock Market Sees Sudden Drop",
    slug: "stock-market-drop-2025",
    content: "Unexpected sell-off hits major global indices...",
    excerpt: "Investors react to latest inflation data and Fed comments.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Finance",
    tags: ["Stock Market", "Inflation", "Economy"],
    author: {
      id: "auth003",
      name: "Richard Lee",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-27T06:10:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1104,
    status: "published",
  },
  {
    id: "nws099",
    title: "Meta Launches New VR Headset",
    slug: "meta-vr-headset-2025",
    content: "New features include retina tracking and haptic feedback...",
    excerpt: "The tech giant redefines virtual reality experience.",
    thumbnail: "/images/thumb/thumb1.avif",
    category: "Technology",
    tags: ["Meta", "VR", "Gadgets"],
    author: {
      id: "auth002",
      name: "Jane Smith",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-27T13:25:00Z",
    isFeatured: false,
    isEditorsPick: false,
    views: 1675,
    status: "published",
  },
  {
    id: "nws100",
    title: "UK Elections: Close Race Expected",
    slug: "uk-election-2025",
    content: "Polls suggest a tight contest between parties...",
    excerpt: "Public opinion divided ahead of key national vote.",
    thumbnail: "/images/thumb/thumb2.avif",
    category: "Politics",
    tags: ["Elections", "UK", "Politics"],
    author: {
      id: "auth001",
      name: "John Doe",
      avatar: "/images/users/user1.jpg",
    },
    createdAt: "2025-04-23T08:15:00Z",
    isFeatured: false,
    isEditorsPick: true,
    views: 2110,
    status: "published",
  },
];
